services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.49.1-noble
    working_dir: /app
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/apps/desktop/node_modules
      - /app/packages/core/node_modules
      - /app/packages/ui/node_modules
    environment:
      - CI=true
      - DISPLAY=:99.0
      - ELECTRON_DISABLE_SANDBOX=1
    command: |
      sh -c "
        apt-get update &&
        apt-get install -y python3-setuptools python3-dev build-essential xvfb &&
        npm install -g pnpm@8.14.0 &&
        pnpm install --frozen-lockfile &&
        pnpm build:deps &&
        pnpm --filter @vibetree/desktop build &&
        cd apps/desktop &&
        npx tsc src/main/test-index.ts --outDir dist/main --target es2020 --module commonjs --esModuleInterop --allowSyntheticDefaultImports --resolveJsonModule &&
        cd node_modules/electron && node install.js && cd ../.. &&
        xvfb-run --auto-servernum --server-args='-screen 0 1280x960x24' -- pnpm exec playwright test --reporter=list
      "